### PR TITLE
Added MemoryStorage

### PR DESCRIPTION
**Pull request by gilamran**

### CODE REVIEW

**Comment by mastertheblaster** [comment]
@gilamran This one is a little bit tricky. Because everything is being stored in memory of the strategy instance. So as a result I will not be able to create 2 in memory capsules and use one for reading and another one for writing. If that's not an issue please ignore.

**Comment by gilamran** [comment]
@mastertheblaster  well, actually this is great for tests... a one time thing, similar to in-memory db. one per test.
This is what I used internally in Business Manager when I wanted to test the data-capsule. I faked the local-storage with an in-memory mock.
Think Test-kit. :-)
WDYT?

**Comment by shahata** [comment]
@gilamran wdyt about what we do in https://github.com/wix/data-capsule/blob/master/test/data-capsule.spec.js ?

```js
const {LocalStorage} = require('node-localstorage');
beforeEach(() => global.localStorage = new LocalStorage('./scratch'));
afterEach(() => global.localStorage.clear());
```

**Comment by gilamran** [comment]
@shahata I like it!.
Not sure if the Memory strategy is useful for other cases now...
You can close this PR, up to you.

**Pull request closed without merging**
