### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by technotronic12**
* upgrade to yoshi 4
* run lint fix
* set node version to 12
* update some other dependencies
* don't use yoshi release, use publish config

### CODE REVIEW

**Comment by technotronic12** [comment]
Currently blocked by https://github.com/wix/yoshi/issues/2082

**Comment by gonengar** [comment]
Are we still blocked?
Sends yoshi released the block

**Comment by gonengar** [comment]
Thanks
Plz update task in jira

**Comment by technotronic12** [comment]
Solved after https://github.com/wix/yoshi/pull/2089

**Pull request merged**
