### PR TITLE
fix(wix-storage): use absolute url for axios req

### LINKED ISSUE #42: Use absolute url for wix-storage strategy
For calls being made to `'/_api/wix-user-preferences-webap`, please use an absolute url (`https://www.wix.com/_api/wix-user-preferences-webap`)

Currently we have a problem that we configured axios's baseUrl configured to be something else, so data-capsule fails as it tries to reach our servers instead of the main wix.

### PR DESCRIPTION
**Pull request by liorcode**
this fixes #42

### CODE REVIEW

**Comment by shahata** [comment]
This is something we intentionally avoid... We don't want to do cross domain requests. Why is this needed? In what app this doesn't work?

**Comment by liorcode** [comment]
In the promote fb ads app, we use a custom base url for axios. So when the data capsule tries to reach `_api/wix-user-preferences-webapp`, it actually tries to reach `www.wix.com/_api/promote-campaigns-manager/_api/wix-user-preferences-webap`
Not cross-domain, just wrong path in this case

**Comment by shahata** [comment]
So why not create an axios instance in your app for those calls?

**Comment by liorcode** [comment]
That would be possible to solve it for my case, but i just thought it's a little weird that 'wix strategy' doesn't include the wix domain :)

**Comment by shahata** [comment]
yeah, but as a best practice we want to make all api calls on the same domain as the page to avoid cross domain issues

**Comment by liorcode** [comment]
I guess it makes sense, but isn't it better to use full domain in order to:
1. Not rely on the global axios (i'm sure I'm not the only one modifying it's base url)
2. Still fail on cross-domain request, but with a relevant error so a user would know cross-domain requests are not allowed

**Comment by shahata** [comment]
Didn't understand. If we use constant domain it will fail on all places that use a different domain. It can't work.

**Comment by liorcode** [comment]
If I understand correctly, this 'wix strategy' would only work if you're already running under "wix.com" domain right? so adding the domain explicitly to the requests won't really make a different?
I mean that it would still fail if you try to use it outside wix (as it does now) but at least the error would make more sense - cross domain error, instead of a "404" (which anyone outside wix or with custom base url is getting)

**Comment by shahata** [comment]
1) there are many wix.com domains (editor.wix.com, www.wix.com, fr.wix.com, etc.)
2) it should also work on user's site, which can be literally any domain

**Comment by liorcode** [comment]
ah, didn't realize it also works for other domains..guess there's a mapping for `_api/wix-user-preferences-webapp` everywhere?

**Comment by shahata** [comment]
correct

**Pull request closed without merging**
